#!/bin/bash
#
#PBS -N dasked 
#PBS -l select=1:ncpus=20:mem=24gb
#PBS -l walltime=24:00:00

#Load in the geo modules needed by various python libraries
module load proj/4.9.3
module load geos/3.5.0
module load python/3.7.2
module load gdal/3.0.4

cd $PBS_O_WORKDIR

#Run first coregistration
source geo/bin/activate
python results-sa-test1.py

#Run point-in-polygon coregistration
source geo2/bin/activate
python results-sa-test2.py 
